kind: Probe
apiVersion: monitoring.coreos.com/v1
metadata:
  name: dgf-website
  namespace: prometheus
spec:
  interval: 60s
  module: http_2xx
  prober:
    url: prometheus-kube-prometheus-blackbox-exporter.prometheus.svc.cluster.local:19115
  targets:
    staticConfig:
      static:
      - http://www.deutsche-glasfaser.de
      - https://www.deutsche-glasfaser.de
---
kind: Probe
apiVersion: monitoring.coreos.com/v1
metadata:
  name: dgf-router1
  namespace: prometheus
spec:
  interval: 60s
  module: if_mib
  prober:
    url: snmp-exporter-prometheus-snmp-exporter.prometheus.svc.cluster.local:9116/snmp
  targets:
    staticConfig:
      static:
      - 10.0.1.71
