kind: Probe
apiVersion: monitoring.coreos.com/v1
metadata:
  name: dgf-website
  namespace: monitoring
spec:
  interval: 60s
  module: http_2xx
  prober:
    url: prometheus-kube-prometheus-blackbox-exporter.prometheus.svc.cluster.local:19115
  targets:
    staticConfig:
      static:
      - http://www.deutsche-glasfaser.de
      - https://www.deutsche-glasfaser.de
