apiVersion: v1
kind: Service
metadata:
  name: telegraf-snmp
  namespace: prometheus
spec:
  ports:
  - port: 11162
    protocol: UDP
    targetPort: 11162
    nodePort: 30001
  selector:
    app.kubernetes.io/name: telegraf
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-pub
  namespace: prometheus
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
    nodePort: 30002
  selector:
    app.kubernetes.io/name: prometheus
  type: NodePort
